# Generated by Django 4.2.6 on 2025-03-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_using_social_avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Học sinh'), (2, 'Giáo viên'), (3, 'Quản trị viên')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
