# Generated by Django 4.2.6 on 2025-03-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_semester_subject_subjectscore_studentscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectscore',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Học kỳ 1'), (2, 'Học kỳ 2')]),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
