# Generated by Django 4.2.6 on 2025-03-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_subjectscore_semester_delete_semester'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentscore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
