# Generated by Django 4.2.20 on 2025-04-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='pass_score',
            field=models.FloatField(default=5.0),
        ),
    ]
